export {
  Add01Icon as AddIcon,
  Alert02Icon as AlertIcon,
  Archive02Icon as ArchiveIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as ChevronLeftIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowUp01Icon as ChevronUpIcon,
  Attachment01Icon as AttachmentIcon,
  Book02Icon as BookIcon,
  Bookmark02Icon as BookmarkIcon,
  Brain02Icon as BrainIcon,
  BubbleChatIcon as ChatIcon,
  Calculator01Icon as CalculatorIcon,
  Cancel01Icon as CloseIcon,
  Clock01Icon as ClockIcon,
  CloudIcon,
  CodeIcon,
  CommandIcon,
  Copy01Icon as CopyIcon,
  CpuIcon,
  Database02Icon as DatabaseIcon,
  Delete02Icon as DeleteIcon,
  Download01Icon as DownloadIcon,
  Edit02Icon as EditIcon,
  EyeIcon,
  File01Icon as FileIcon,
  Folder02Icon as FolderIcon,
  GitBranchIcon,
  GlobeIcon,
  Idea01Icon as IdeaIcon,
  Image01Icon as ImageIcon,
  InformationCircleIcon as InfoIcon,
  Key01Icon as KeyIcon,
  Layers01Icon as LayersIcon,
  Link04Icon as LinkIcon,
  LockIcon,
  MagicWand01Icon as MagicIcon,
  Menu01Icon as MenuIcon,
  MoreHorizontalIcon as MoreIcon,
  Moon02Icon as MoonIcon,
  PanelLeftIcon,
  PanelRightIcon,
  Pdf01Icon as PdfIcon,
  Pin02Icon as PinIcon,
  Plug01Icon as PlugIcon,
  Refresh01Icon as RefreshIcon,
  Rocket01Icon as RocketIcon,
  Search01Icon as SearchIcon,
  Sent02Icon as SendIcon,
  Settings02Icon as SettingsIcon,
  Shield01Icon as ShieldIcon,
  SlidersHorizontalIcon as SlidersIcon,
  SparklesIcon,
  StarIcon,
  StopIcon,
  Sun02Icon as SunIcon,
  Tag01Icon as TagIcon,
  Tick02Icon as CheckIcon,
  Upload01Icon as UploadIcon,
  User03Icon as UserIcon,
  Wrench01Icon as WrenchIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons"
